### ISSUE TITLE
Landing Page Designing

### ISSUE THREAD

**Issue by aad99bxp** [aad99bxp/Digital-Business-Card#1]
Currently there is no home page or a landing page.  The following screenshot is the preview  when someone lands on the deployment link:
![image](https://github.com/user-attachments/assets/0e4a2d38-a217-4a4f-8f51-97b3f0c6766b)

Design a homepage / landing page with filenames as index.html and indexpage.css.

**Necessary Requirements:**
1. Page should contain all the necessary information regarding the Digital Business Card.
2. Features Section
3. Header
4. Footer
5. Login button which should navigate the user to login.html page. 
6. Design should be responsive across mobile and desktop devices.

**Comment by Piyushkumarj** [comment]
create a pull request review and merge
