### ISSUE TITLE
New Template for Digital Card for Professionals

### ISSUE THREAD

**Issue by aad99bxp** [aad99bxp/Digital-Business-Card#2]
The current version of code has only one specific design as below:

![3](https://github.com/user-attachments/assets/44fdb62f-006d-4621-b9d3-f21922cf8bb7)

This design is suitable for a company representative. However, upon a primary interaction with potential users, it is found that more design templates are needed as per different use cases. One such use case is a design for individual professionals. 

Design a template for the same.

Constraints:
1. Page should contain all the necessary information regarding the Digital Business Card.
2. Design should be responsive across mobile and desktop devices.

**Comment by ravish12413** [comment]
My first contribution just got merged.

**Comment by Piyushkumarj** [comment]
Create a pull Request

**Comment by aad99bxp** [comment]
Resolved !
